- name: 下载etcd二进制文件
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl
  tags: upgrade_k8s

# 注册变量p，根据p的stat信息判断是否已经生成过etcd证书，如果没有，下一步生成证书
# 如果已经有etcd证书，为了保证整个安装的幂等性，跳过证书生成的步骤

- name: 创建etcd工作目录
  file: name=/var/lib/etcd state=directory

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/usr/lib/systemd/system/etcd.service

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  tags: upgrade_k8s
